In [32]:
# to create the numpy array using range function
n1= np.array(range(1,10))
print(n1)

[1 2 3 4 5 6 7 8 9]


In [33]:
import numpy as np
n1=np.arange (1,10)
print(n1)

[1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np 
n2=np.arrange (1.5,10.5)
print(n2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [7]:
# attributes of numpy array..
n1=np.array([[1,2],[3,4]])
print(n1)
print(n1.ndim)


[[1 2]
 [3 4]]
2


In [8]:
# zeros 
n1 = np.zeros(4)
print(n1)

[0. 0. 0. 0.]


In [9]:
# 2d array 
n2=np.zeros((2,3),dtype=int)
print(n2)

[[0 0 0]
 [0 0 0]]


In [10]:
# ones method : 1d array 
n1=np.ones(5,dtype=int)
print(n1)

[1 1 1 1 1]


In [11]:
# 2d array
n2=np.ones((2,2),dtype=int)
print(n2)

[[1 1]
 [1 1]]


In [12]:
# to print identity matrix 
n1=np.eye((3),dtype=int)
print(n1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [13]:
# to print the diagonal values
n1=np.diag([2,3,4])
print(n1)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [14]:
# full method
n1=np.full(4,7)# full(size,element)
print(n1)

[7 7 7 7]


In [15]:
# 2d array
n2=np.full((2,3),6)
print(n2)

[[6 6 6]
 [6 6 6]]


In [18]:
# to print the matrix addition..
a=np.array ([1,2]),[2,4]])
print(a)
print('--------------')
b=np.array([[1,1]],[3,3]])
print('-----')
print(a+b)
print('matrix multiplication')


SyntaxError: unmatched ']' (1026596590.py, line 2)

In [20]:
# matrix multiplication using dot()method
print(a.dot(b))

NameError: name 'a' is not defined

In [21]:
# using random method we can create numpy..
# To generate single random number...
n1=np.random radient(10,20)


SyntaxError: invalid syntax (963161693.py, line 3)

In [22]:
# To generate the number of random number....
np,random.radient  (20,90,5)

NameError: name 'random' is not defined

In [23]:
# reshape ()
# to convrt the 1-d to n-d array ..
print(n1)


[7 7 7 7]


In [24]:
np.arrange(4).reshape(4,1)

AttributeError: module 'numpy' has no attribute 'arrange'

In [25]:
import numpy as np
print(n1)

[7 7 7 7]


In [28]:
#To 3-d array using reshape method..
n1=np.arrange(24).reshape()
#(number of table,number of rows )

AttributeError: module 'numpy' has no attribute 'arrange'

In [31]:
# resize :n-d to n-d array....
a1=np.array ([1,2],[3,4]])
print(a1)
print(np.resize the )


SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (1303429530.py, line 2)

In [34]:
# ravel():
# to convert the n-d to 1-d array....
a1=np.array([[1,2,3],[4,5,7]])


pandas
.it is data science library
. pandas abbrevation as python data analysis library
. is is a open source libarary
. it is a mainly use for data analysis and data 
manipulations
. it deals with two different data structures
1. series data structure like 1d arrray
2. data frame data structure like 2d array
 . first we need to import pandas as pd
 .

seieus data structure 
    . using list, dictionary, numpy
    . syntax:
           pandas.series (list/dict/numpy)
           

In [36]:
# to create series data structure using list 
import pandas as pd
s1=pd.Series([1,2,3])
print(s1)

0    1
1    2
2    3
dtype: int64


In [38]:
# to create series data structure using dict.
d1={'name':'ajay','rollno':420}
s2=pd.Series(d1)
print(s2)

name      ajay
rollno     420
dtype: object


In [39]:
# to create series data structure using numpy array 
n1=np.arange (1,5)
s3=pd.Series(n1)
print(s3)

0    1
1    2
2    3
3    4
dtype: int32


In [40]:
# to change the index names using index
s1=pd.Series(['ALTS','SRIT'])
s1.index=['A','B']
print(s1)

A    ALTS
B    SRIT
dtype: object


In [41]:
# to access the values from the series data structure
s1['A']

'ALTS'

In [48]:
# to update the multiple record..
print(s1)
s1=s1.replace(to_replace=['ALTS','PVKK'])Values=100
s1

SyntaxError: invalid syntax (2479697057.py, line 3)

In [50]:
# Delete the rows using drop method ..
print(s1)
s1=s1. Drop(lables='A')
print(s1)

A    ALTS
B    SRIT
dtype: object


AttributeError: 'Series' object has no attribute 'Drop'

In [51]:
-Data Frame:
        -using dictionary and numpy 2-d array
        -syntax:
                pd.DataFrame(dictionary/numpy2-d array)

SyntaxError: invalid syntax (175723679.py, line 1)

In [54]:
#To create the dataframe using dictionary..
d1={'Name':['Narmada','netra','nandini','aadya'],'rollno',:[311,511,310]}
df=

SyntaxError: invalid syntax (65658422.py, line 2)

In [53]:
#To know the row values..
df.values

NameError: name 'df' is not defined

In [55]:
# To change the index name..
df.index=['A','B','C']

NameError: name 'df' is not defined

In [57]:
# To add new record to dataFrame..
df.loc['D']='nani',320
df

NameError: name 'df' is not defined